stages:
  preprocess:
      cmd: python -m ml.src.visdrone_prepare
      deps:
        - ml/src/visdrone_prepare.py
        - params.yaml
        - data/images/train
        - data/images/val
        - data/raw/labels/train
        - data/raw/labels/val
      outs:
        - data/labels/train
        - data/labels/val
      params:
        - train.train_images
        - train.val_images
        - train.train_labels
        - train.val_labels
        - train.yolo_train_labels
        - train.yolo_val_labels
  
  train_smoke:
    cmd: python ml/src/smoke_train.py 
    deps:
      - ml/src/smoke_train.py
      - params.yaml
    outs:
      - models/smoke
      
  train:
    cmd: python -m ml.train
    deps:
      - ml/train.py
      - ml/models/assigner_fcos.py
      - ml/models/losses_fcos.py
      - ml/models/detector.py
      - ml/models/postprocess_fcos.py
      - ml/data/yolo_dataset.py
      - ml/data/collate.py
      - params.yaml
      - data/yolo
    outs:
      - models/custom/best.pt
      - models/custom/last.pt

  
