stages:
  preprocess:
      cmd: python -m ml.src.visdrone_prepare
      deps:
        - ml/src/visdrone_prepare.py
        - params.yaml
        - data/raw/labels/train
        - data/raw/labels/val
      outs:
        - data/yolo/labels/train
        - data/yolo/labels/val
      params:
        - train.train_images
        - train.val_images
        - train.train_labels
        - train.val_labels
        - train.yolo_train_labels
        - train.yolo_val_labels
      
  train:
    cmd: python -m ml.train
    deps:
      - ml/train.py
      - ml/models/assigner_fcos.py
      - ml/models/losses_fcos.py
      - ml/models/detector.py
      - ml/models/postprocess_fcos.py
      - ml/data/yolo_dataset.py
      - ml/data/collate.py
      - params.yaml
      - data/yolo
    outs:
      - models/custom/best.pt
      - models/custom/last.pt

  
  yolo_train_new:
    cmd: python -m ml.yolo_train --params params.yaml --cfg-key yolo_new
    deps:
      - ml/yolo_train.py
      - params.yaml
      - data.yaml
      - data/yolo/images/train
      - data/yolo/images/val
      - data/yolo/labels/train
      - data/yolo/labels/val
    params:
      - yolo_train

  yolo_train_fast:
    cmd: python -m ml.yolo_train --params params.yaml --cfg-key yolo_fast
    deps:
      - ml/yolo_train.py
      - params.yaml
      - data.yaml
      - data/yolo/images/train
      - data/yolo/images/val
      - data/yolo/labels/train
      - data/yolo/labels/val
    params:
      - yolo_train